title: Willis Oguwike 
logo: willis_oguwike.jpg
description: A data analyst with over one year of experience using microsoft excel for data automation, Structured Query Language (SQL) for data manipulation and interrogation and, Power BI for business intelligence report.


#show_downlods: true
#google_analythics:
theme: jekyll-theme-minimal
